#!/usr/bin/env python

import sys
import subprocess
import re

    
def main():
    if len(sys.argv) == 2: 

	device = sys.argv[1]

	out = subprocess.Popen(["blkid","-d","-s","LABEL",device], stdout=subprocess.PIPE)
	mountPoint = out.communicate()[0]
	if out.returncode != 0:	
		exit(1)

	regex =  re.compile(r'(?<=LABEL=\")([^"]|\\")*', re.IGNORECASE)
	matches = regex.search(mountPoint)
	mountPoint = matches.group()

	print mountPoint	

    else:
	print "Usage: getDVDTitle <device>"


main()
